# Generated by Django 6.0.3 on 2026-03-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=100)),
                ('data_moris', models.DateField()),
                ('idade', models.IntegerField()),
                ('sexu', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('enderesu', models.CharField(max_length=100)),
                ('munisipiu', models.CharField(max_length=100)),
                ('eskola_anterior', models.CharField(max_length=100)),
            ],
        ),
    ]
