# Generated by Django 6.0.3 on 2026-03-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_estudante/'),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
