# Generated by Django 6.0.3 on 2026-03-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_estudante_foto_alter_estudante_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='departamentu',
            field=models.CharField(choices=[('', 'Hili Departamentu...'), ('Geologia_Petroleo', 'Geologia e Petroleo'), ('Engenharia_Civil', 'Engenharia Civil'), ('Engenharia_Mecanica', 'Engenharia Mecanica'), ('Engenharia_Informatica', 'Engenharia Informatica'), ('Engenharia_Eleticidade_e_Eletronica', 'Engenharia Eleticidade e Eletronica')], default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudante',
            name='sexu',
            field=models.CharField(choices=[('M', 'Mane'), ('F', 'Feto')], max_length=1),
        ),
    ]
